### ISSUE TITLE
Export as abc gives "IndexError list index out of range"

### ISSUE THREAD

**Issue by StenApp** [haekb/io_scene_lithtech#30]
Python: Traceback (most recent call last):
  File "C:\Users\Sten\Downloads\blender-2.93.18-windows-x64\2.93\scripts\addons\Lithtech\exporter.py", line 60, in execute
    model = ModelBuilder().from_armature(armature_object)
  File "C:\Users\Sten\Downloads\blender-2.93.18-windows-x64\2.93\scripts\addons\Lithtech\builder.py", line 164, in from_armature
    if vertex.weights[0].node_index == bone_index:
IndexError: list index out of range

location: <unknown location>:-1

@Psycrow101 any idea of what's wrong here?
[britishpolicehat.ltb.txt](https://github.com/haekb/io_scene_lithtech/files/15100470/britishpolicehat.ltb.txt)

**Comment by Five-Damned-Dollarz** [comment]
There's no vertices assigned to any vertex group:

> For every bone in your armature, the mesh must have a corresponding vertex group with the same name. Assign vertices you want to be affected by the bone here with a weight 1.

[Source](https://github.com/haekb/io_scene_lithtech/blob/master/doc/abc-v6-export-basics.md)

Edit: Now that I'm looking at the documentation again, I see it's missing the crucial point that *all* vertices must be assigned to a vertex group (the engine requires it). I'll update the documentation in my fork since @haekb isn't active to accept new pull requests.

**Comment by StenApp** [comment]
> There's no vertices assigned to any vertex group:
> 
> > For every bone in your armature, the mesh must have a corresponding vertex group with the same name. Assign vertices you want to be affected by the bone here with a weight 1.
> 
> [Source](https://github.com/haekb/io_scene_lithtech/blob/master/doc/abc-v6-export-basics.md)
> 
> Edit: Now that I'm looking at the documentation again, I see it's missing the crucial point that _all_ vertices must be assigned to a vertex group (the engine requires it). I'll update the documentation in my fork since @haekb isn't active to accept new pull requests.

Can you please make a fix?

**Comment by StenApp** [comment]
Closed in favor of https://github.com/Five-Damned-Dollarz/io_scene_lithtech/issues/2#issue-2263529715

this repository is abandoned
